// Bridges the Vite SPA build into the Hydrogen/Oxygen worker build.
// Run AFTER `vite build`, BEFORE `shopify hydrogen build`.
//
// 1. Copies dist/assets/* into public/assets/* so Oxygen serves the SPA bundle as
//    static files (cached at the edge).
// 2. Reads dist/index.html and writes it as a JS module that the splat route imports
//    and returns as the HTML response body.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

const VITE_DIST = path.join(ROOT, 'dist-spa');
const PUBLIC_ASSETS = path.join(ROOT, 'public/assets');
const SHELL_OUT = path.join(ROOT, 'app/spa-shell.generated.js');

const INDEX_HTML = path.join(VITE_DIST, 'index.html');
const DIST_ASSETS = path.join(VITE_DIST, 'assets');

if (!fs.existsSync(INDEX_HTML)) {
  console.error(`Missing ${INDEX_HTML}. Run \`npm run build:spa\` first.`);
  process.exit(1);
}

fs.rmSync(PUBLIC_ASSETS, { recursive: true, force: true });
fs.mkdirSync(PUBLIC_ASSETS, { recursive: true });
fs.cpSync(DIST_ASSETS, PUBLIC_ASSETS, { recursive: true });

const html = fs.readFileSync(INDEX_HTML, 'utf8');
const escaped = html.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
fs.writeFileSync(SHELL_OUT, `// Auto-generated by scripts/prepare-oxygen.mjs. Do not edit.\nexport default \`${escaped}\`;\n`);

console.log(`Wrote ${PUBLIC_ASSETS}/ and ${SHELL_OUT}`);
